# Generated by Django 5.2 on 2025-04-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='category',
            field=models.CharField(choices=[('tacos', 'Тако'), ('burritos', 'Буррито'), ('nachos', 'Начос'), ('burgers', 'Бургеры'), ('sauces', 'Соусы'), ('drinks', 'Напитки')], default='tacos', max_length=20),
        ),
    ]
