# Generated by Django 5.2 on 2025-04-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_cart_cartitem_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличными'), ('card', 'Картой онлайн'), ('card_courier', 'Картой курьеру')], default='card', max_length=20),
        ),
    ]
